FROM python:3.11-slim-bookworm

WORKDIR /app

COPY server/requirements-cpu.txt ./requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY server/ ./server/

EXPOSE 8000
CMD ["python3", "-m", "uvicorn", "server.core.app:app", "--host", "0.0.0.0", "--port", "8000"]
